<?php
session_start();
if(isset($_SESSION['name']))
{
    if(isset($_SESSION['P-name']))
    {
        if($_SESSION['pdf'] == "True")
        {
            $html = '<head>
        <meta charset="UTF-8">
        <title>Report</title>
        <link rel="stylesheet" href="css/bootstrap.css">
        <style>
            @import url(http://fonts.googleapis.com/css?family=Bree+Serif);
            body, h1, h2, h3, h4, h5, h6{
                font-family:  serif;
            }
        </style>
    </head>

    <body style="background-color: #b2ebf2">
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                <h1>
                    <a href="#">
                        <img src="../img/logo.png">
        E-convoy
                    </a>
                </h1>
            </div>
            <div class="col-xs-6 text-right">
                <h1>';
            $html .=  $_SESSION['print'];
            $temp1='Report</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-5  text-left">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>To :<a href="#">';
            $temp2='</a></h4>
                    </div>
                    <div class="panel-body">
                        <p>

                            Fir No:';


            $temp3 = '</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- / end client details section -->
        <div class="row text-left">
            <div class="col-xs-12">
                <p>
                    <strong>
                        <h1>
                            Welcome,<br>
                        </h1>
                    </strong>

                <p>This is an e-copy of fir report submitted by you to the police force.The report has been auto generated by the system.The comments of police force are:';

            $html.= $temp1 .$_SESSION['P-name'].$temp2.$_SESSION['firno'].'<br>Date: '.date('d/m/Y').$temp3.$_SESSION['reply'].' </p>
                </p>
                <br>
                <h4>Yours Truly:</h4>
                <h5>Admin</a></h5>
            </div>
        </div>
        </div>
    </body>';



            //==============================================================
            //==============================================================
            //==============================================================

            $name ='\ '.$_SESSION['P-name'].'.pdf';
            $path1='pdfoutput' ;
            $path1.= $name;


            include("mpdf/mpdf.php");
            $mpdf=new mPDF('c');
            $mpdf->WriteHTML($html);
            $mpdf->Output($path1,'F');
            header('Location:http://localhost:90/econvoy/fir.php');
            exit;

            //==============================================================
            //==============================================================
            //==============================================================

        }
        else
        {
            $_SESSION['error'] == "error";
            header('Location:http://localhost:90/econvoy/fir.php');
        }
    }


}
else
{
    $_SESSION['name'] = "logout";
    header('Location:http://localhost:90/econvoy/');
}

?>